<?php

namespace Troiswa\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends EntityRepository
{

    public function getNbFilmByCategorie()
    {

        $req=$this->getEntityManager()->createQuery(

            "Select count(f.id) as nbFilm, c.titre
            From TroiswaPublicBundle:Film f
            Left join f.categorie c
            group by c.id "

            );

        return $req->getResult();
    }
}
